/**
 * Strict Tool Use canonical fixture — Phase 8 (LAND-FIXTURE).
 *
 * One real JARVIS input → the strict-tool-use JSON the agent emits.
 * Used by:
 *   - apps/web/components/landing/EngineSection.tsx (UI-SPEC §5d "Plucked verbatim from
 *     packages/jarvis-core/tests/strict-tool-use.fixture.ts — no edits")
 *   - Future contract tests asserting the canonical README example still routes correctly
 *
 * The input is the README canonical example (README.md lines 33-39).
 * The output is the real shape Claude Sonnet 4.6 emits via Anthropic Strict Tool Use
 * for this input, conforming to the Zod schemas in packages/jarvis-core/src/tools/.
 *
 * Field names match the live Zod schemas EXACTLY:
 *   - create_event:  { title, start, end, calendar_id?, description? }
 *     (see packages/jarvis-core/src/tools/create-event.ts)
 *   - create_task:   { title, priority?, status?, due?, project_ids? }
 *     (see packages/jarvis-core/src/tools/create-task.ts)
 *
 * Date math: "saturday" + "friday afternoon" from a 2026-05-25 (Monday) anchor.
 *   - 2026-05-30 is a Saturday (verified: `date -j -f "%Y-%m-%d" "2026-05-30" "+%A"`)
 *   - 2026-05-29 is a Friday  (verified: `date -j -f "%Y-%m-%d" "2026-05-29" "+%A"`)
 *   - "friday afternoon" defaults to 15:00 local under the chrono-node pre-parser
 *   - timezone offset -04:00 = America/New_York during DST (mid-May)
 *
 * DO NOT EDIT THIS FILE without re-running the input through the live JARVIS pipeline
 * and copying the resulting tool_use blocks verbatim. This file is referenced in the
 * public landing's "source of truth" claim — drift here is a public-credibility leak.
 */

export interface StrictToolUseFixture {
  readonly input: string;
  readonly output: {
    readonly tool_use: ReadonlyArray<{
      readonly type: "tool_use";
      readonly name:
        | "create_task"
        | "create_capture"
        | "create_event"
        | "remember_fact"
        | "ask_clarification";
      readonly input: Record<string, unknown>;
    }>;
  };
}

export const STRICT_TOOL_USE_FIXTURE: StrictToolUseFixture = {
  input: "dinner with anna 8pm saturday. buy her flowers friday afternoon",
  output: {
    tool_use: [
      {
        type: "tool_use",
        name: "create_event",
        input: {
          title: "Dinner with Anna",
          start: "2026-05-30T20:00:00-04:00",
          end: "2026-05-30T21:00:00-04:00",
        },
      },
      {
        type: "tool_use",
        name: "create_task",
        input: {
          title: "Buy flowers",
          priority: "P2",
          status: "not started",
          due: "2026-05-29T15:00:00-04:00",
        },
      },
    ],
  },
} as const;
