"use client";

import { useEffect, useRef } from "react";
import { usePathname } from "next/navigation";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { streamJarvis } from "@/components/jarvis/jarvis-stream-client";
import { saveJarvisTurn } from "@/app/actions/jarvis-turns";
import type {
  ScrollbackAction,
  ScrollbackClarification,
  ScrollbackTurn,
} from "./jarvis-types";
import { useVoiceSettings } from "@/lib/voice/use-voice-settings";
import { stripSystemTags } from "@/lib/jarvis/strip-system-tags";
import { invalidateAfterJarvisAction } from "@/lib/jarvis/invalidate-after-action";
// Phase 10 Plan 10-04 (LAT-02) — client-side sentence boundary splitter.
// Same wiring pattern as JarvisConsole: per-sentence dispatch on each
// completed sentence so TTS fetches fire while later sentences are still
// being generated by Claude.
import { splitDeltas } from "@/lib/voice/sentence-splitter";
// Phase 9 / TEL-01 — voice-stage collector binding. setActiveTurnId binds the
// turnId returned by the server (SSE turn-start event); collectStage(vad_end_at)
// then lands the LOCALLY-captured timestamp piped through the transcript event.
import {
  collectStage,
  setActiveTurnId,
} from "@/lib/voice/voice-stage-collector";

/**
 * GlobalJarvisHandler — voice transcript pipeline for pages WITHOUT the
 * full JARVIS Console mounted.
 *
 * Voice listening is global (JarvisListener in (app)/layout.tsx grabs the
 * mic + transcribes) but JarvisConsole only mounts on /today. Without this
 * handler, "Hey Jarvis, add task X" from /calendar would transcribe, fire
 * the jarvis-voice-transcript event, and nobody would pick it up.
 *
 * This component owns the same submit → action → TTS chain JarvisConsole
 * runs, minus the scrollback UI:
 *   - POST /api/jarvis with the transcript
 *   - Render action receipts as toast notifications
 *   - Dispatch jarvis-voice-speak-sentence per sentence + jarvis-voice-end-of-turn
 *     on response completion (TTS pipelined dispatch + FSM cycle, LAT-02)
 *
 * Mount-once contract: the listener is bound ONLY when JarvisConsole is NOT
 * mounted on the current page (currently /today). Avoids double-processing.
 */
/**
 * Fire-and-forget save. Mirrors JarvisConsole.persistTurn byte-for-byte:
 * a failed save is logged but never bubbles — scrollback persistence is
 * best-effort and must not disrupt the toast/TTS/FSM pipeline.
 */
function persistTurn(turn: ScrollbackTurn): void {
  void saveJarvisTurn({
    id: turn.id,
    kind: turn.kind,
    text: turn.kind === "user" ? turn.text : null,
    textDelta: turn.kind === "assistant" ? turn.textDelta : null,
    actions: turn.kind === "assistant" ? turn.actions : [],
    clarification:
      turn.kind === "assistant" ? turn.clarification ?? null : null,
    status: turn.kind === "assistant" ? turn.status : null,
    errorMessage:
      turn.kind === "assistant" ? turn.errorMessage ?? null : null,
    createdAt: turn.createdAt.toISOString(),
  }).catch((err) => {
    console.warn("[jarvis] persistTurn failed (non-fatal)", err);
  });
}

export function GlobalJarvisHandler({ userId }: { userId: string }) {
  const pathname = usePathname();
  const { settings: voiceSettings } = useVoiceSettings();
  const voiceSettingsRef = useRef(voiceSettings);
  voiceSettingsRef.current = voiceSettings;
  // Issue #17: refresh the lists a JARVIS action touched directly on the
  // client (Realtime echo is best-effort and never covers gcal events).
  const queryClient = useQueryClient();

  // /today owns its own jarvis-voice-transcript handler via JarvisConsole.
  // Bind the global handler everywhere else under (app).
  const isConsolePage = pathname === "/today";

  useEffect(() => {
    if (isConsolePage) return;

    let abort: AbortController | null = null;

    function handleVoiceTranscript(e: Event) {
      // Phase 9 / TEL-01: detail now also carries sttDoneAt (epoch ms or null)
      // read off the /api/jarvis/stt response header by JarvisListener, AND
      // vadEndAt (epoch ms) captured LOCALLY in JarvisListener.onSpeechEnd
      // and piped through here for deferred collectStage inside onTurnStart.
      const detail = (
        e as CustomEvent<{
          transcript: string;
          sttDoneAt?: number | null;
          vadEndAt?: number;
          source?: string;
        }>
      ).detail;
      if (!detail?.transcript?.trim()) return;
      // Desktop-originated transcripts were already executed server-side
      // (voice/transcript route runs the JARVIS turn and the desktop app
      // plays the TTS). Re-submitting here ran a SECOND divergent turn —
      // the desktop and browser would show different responses and actions
      // could double-fire. Receipts for these turns surface via the
      // jarvis-tool-call listener below instead.
      if (detail.source === "desktop") return;
      const sttDoneAt = detail.sttDoneAt ?? null;
      const vadEndAt = detail.vadEndAt;

      // Cancel any in-flight call before starting a new one.
      abort?.abort();
      abort = new AbortController();

      // Phase 10 Plan 10-04 (LAT-02) — per-turn sentence dispatch state.
      // Local to this submit closure so every transcript starts fresh.
      let ttsBuffer = "";
      let ttsSeq = 0;

      // Persist this turn to jarvis_turns so it joins the JARVIS conversation
      // record and surfaces live on /today (deduped by client UUID). Mirrors
      // JarvisConsole's persist-user-immediately / persist-assistant-on-done
      // semantics. Best-effort: persistTurn never bubbles.
      const userTurnId = crypto.randomUUID();
      const assistantTurnId = crypto.randomUUID();
      const userTurn: ScrollbackTurn = {
        kind: "user",
        id: userTurnId,
        text: detail.transcript,
        createdAt: new Date(),
      };
      persistTurn(userTurn);
      const assistant: {
        kind: "assistant";
        id: string;
        textDelta: string;
        actions: ScrollbackAction[];
        clarification: ScrollbackClarification | undefined;
        createdAt: Date;
        status: "streaming" | "done" | "error";
        errorMessage?: string;
      } = {
        kind: "assistant",
        id: assistantTurnId,
        textDelta: "",
        actions: [],
        clarification: undefined,
        createdAt: new Date(),
        status: "streaming",
      };

      void streamJarvis(
        {
          input: detail.transcript,
          history: [],
          parsedDates: [],
          parsedPriority: undefined,
          slashCommand: null,
          linkedProjectIds: [],
          linkedHashtags: [],
        },
        {
          onText: (delta) => {
            // Phase 10 Plan 10-04 (LAT-02) — per-sentence TTS dispatch as
            // text deltas arrive. GlobalJarvisHandler always handles VOICE
            // transcripts (isVoice: true hardcoded — this component is only
            // mounted on non-/today routes and is only invoked from the
            // voice transcript event).
            assistant.textDelta += delta;
            const { sentences, remainder } = splitDeltas(ttsBuffer, delta);
            ttsBuffer = remainder;
            for (const s of sentences) {
              const cleaned = stripSystemTags(s).trim();
              if (!cleaned) continue;
              const seq = ttsSeq++;
              window.dispatchEvent(
                new CustomEvent("jarvis-voice-speak-sentence", {
                  detail: {
                    text: cleaned,
                    seq,
                    voiceId: voiceSettingsRef.current.voiceId,
                    isVoice: true,
                  },
                }),
              );
            }
          },
          // Phase 9 / TEL-01 — first SSE frame; server-generated turnId. Bind
          // the collector to THIS turn FIRST, THEN collectStage(vad_end_at)
          // so the locally-captured timestamp lands against the now-bound row.
          // (stt_done_at is captured server-side via the X-Jarvis-Stt-Done-At
          // request header at stream start — Plan 09-01. Don't double-write.)
          onTurnStart: (data) => {
            setActiveTurnId(data.turnId);
            if (vadEndAt != null && Number.isFinite(vadEndAt)) {
              collectStage("vad_end_at", new Date(vadEndAt));
            }
          },
          onQueued: (data) => {
            // Receipts (toasts) still surface via onAction with the real
            // result. Here we ALSO push a queued placeholder action onto the
            // persisted assistant turn so the scrollback receipt matches
            // JarvisConsole's onQueued shape.
            assistant.actions.push({
              toolUseId: data.toolUseId,
              name: data.name as ScrollbackAction["name"],
              status: "queued",
            });
          },
          onClarification: (data) => {
            toast(data.question, {
              description: "Tap to reply from /today",
              duration: 8000,
            });
            assistant.clarification = {
              toolUseId: data.toolUseId,
              question: data.question,
              options: data.options ?? [],
              suggestedAction: data.suggestedAction ?? null,
              answered: false,
            };
          },
          onAction: (data) => {
            // Record the action on the persisted assistant turn regardless of
            // ok — mirror JarvisConsole.onAction (upgrade existing queued
            // placeholder by toolUseId, else append) so the scrollback receipt
            // persists. Toast behavior below is unchanged.
            const existing = assistant.actions.find(
              (a) => a.toolUseId === data.toolUseId,
            );
            if (existing) {
              existing.status = "done";
              existing.result = data.result as ScrollbackAction["result"];
            } else {
              assistant.actions.push({
                toolUseId: data.toolUseId,
                name: data.name as ScrollbackAction["name"],
                status: "done",
                result: data.result as ScrollbackAction["result"],
              });
            }
            if (!data.result?.ok) {
              toast.error(
                data.result?.error ?? "JARVIS action failed",
              );
              return;
            }
            // Issue #17: refresh the lists this action touched so the change
            // shows immediately on whatever page is mounted, not just on the
            // Realtime echo. Fires once per action → covers multi-action batches.
            invalidateAfterJarvisAction(queryClient, data.name, userId);
            const receipt = data.result.receipt ?? {};
            const summary =
              typeof (receipt as { title?: unknown }).title === "string"
                ? `${prettyToolName(data.name)}: ${(receipt as { title: string }).title}`
                : `${prettyToolName(data.name)} filed`;
            toast.success(summary, { duration: 4000 });
          },
          onDone: () => {
            // Phase 10 Plan 10-04 (LAT-02) — final flush + butler-ack
            // fallback + end-of-turn signal. Same pattern as JarvisConsole.

            // Final flush: emit any unfinished tail as the last sentence.
            if (ttsBuffer.trim()) {
              const cleaned = stripSystemTags(ttsBuffer).trim();
              if (cleaned) {
                const seq = ttsSeq++;
                window.dispatchEvent(
                  new CustomEvent("jarvis-voice-speak-sentence", {
                    detail: {
                      text: cleaned,
                      seq,
                      voiceId: voiceSettingsRef.current.voiceId,
                      isVoice: true,
                    },
                  }),
                );
              }
              ttsBuffer = "";
            }

            // No sentences emitted — fire butler-ack so the FSM cycles
            // thinking → speaking → listening.
            if (ttsSeq === 0) {
              window.dispatchEvent(
                new CustomEvent("jarvis-voice-speak-sentence", {
                  detail: {
                    text: "Done, sir.",
                    seq: 0,
                    voiceId: voiceSettingsRef.current.voiceId,
                    isVoice: true,
                  },
                }),
              );
              ttsSeq = 1;
            }

            // Signal end-of-turn so the controller drains in-flight fetches
            // and fires onEnd once the AudioQueue empties.
            window.dispatchEvent(
              new CustomEvent("jarvis-voice-end-of-turn", {
                detail: { isVoice: true },
              }),
            );

            // Persist the completed assistant turn (plain prose, no React
            // updater here — GlobalJarvisHandler has no scrollback state — so
            // no flushSync is needed).
            assistant.status = "done";
            persistTurn(assistant);

            abort = null;
          },
          onError: (message) => {
            if (message !== "aborted") {
              toast.error(`JARVIS: ${message}`);
            }
            assistant.status = "error";
            assistant.errorMessage = message;
            persistTurn(assistant);
            abort = null;
          },
        },
        abort.signal,
        // voiceActive — preserve the existing GlobalJarvisHandler default
        // (false). Phase 9 deliberately does NOT change voice-active wiring
        // here; that's a Phase 7 polish item if it lands.
        false,
        // Phase 9 / TEL-01: forward the STT-done-at timestamp; null for the
        // edge case where the header was missing/invalid (the route then
        // records null in stages.sttDoneAt — non-fatal).
        sttDoneAt,
      );
    }

    function handleCancel() {
      abort?.abort();
      abort = null;
    }

    // Receipts for desktop-initiated turns (server-run, relayed via the
    // physical SSE channel). Mirrors the onAction toast above so non-/today
    // pages still show what JARVIS did, without re-running the turn.
    function handleDesktopToolCall(e: Event) {
      const detail = (
        e as CustomEvent<{
          name: string;
          result?: { ok?: boolean; error?: string; receipt?: unknown };
        }>
      ).detail;
      if (!detail?.name) return;
      if (detail.result && detail.result.ok === false) {
        toast.error(detail.result.error ?? "JARVIS action failed");
        return;
      }
      // Issue #17: desktop-run action mutated the same tables — refresh.
      invalidateAfterJarvisAction(queryClient, detail.name, userId);
      const receipt = (detail.result?.receipt ?? {}) as { title?: unknown };
      const summary =
        typeof receipt.title === "string"
          ? `${prettyToolName(detail.name)}: ${receipt.title}`
          : `${prettyToolName(detail.name)} filed`;
      toast.success(summary, { duration: 4000 });
    }

    window.addEventListener("jarvis-voice-transcript", handleVoiceTranscript);
    window.addEventListener("jarvis-cancel", handleCancel);
    window.addEventListener("jarvis-tool-call", handleDesktopToolCall);
    return () => {
      window.removeEventListener("jarvis-voice-transcript", handleVoiceTranscript);
      window.removeEventListener("jarvis-cancel", handleCancel);
      window.removeEventListener("jarvis-tool-call", handleDesktopToolCall);
      abort?.abort();
    };
  }, [isConsolePage, queryClient, userId]);

  return null;
}

function prettyToolName(name: string): string {
  switch (name) {
    case "create_task":
      return "Task";
    case "create_capture":
      return "Capture";
    case "create_event":
      return "Event";
    case "remember_fact":
      return "Fact";
    case "ask_clarification":
      return "Clarification";
    case "create_person":
      return "Person";
    case "link_people":
      return "People linked";
    default:
      return name;
  }
}
