import type { BriefingSource } from "./types";

export const briefingSources: BriefingSource[] = [
  {
    id: "openai-news",
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    kind: "rss",
    category: "labs",
    weight: 1.6,
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    url: "https://www.anthropic.com/news/rss.xml",
    kind: "rss",
    category: "labs",
    weight: 1.55,
  },
  {
    id: "deepmind-blog",
    name: "Google DeepMind",
    url: "https://deepmind.google/discover/blog/rss.xml",
    kind: "rss",
    category: "labs",
    weight: 1.5,
  },
  {
    id: "google-ai",
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    kind: "rss",
    category: "labs",
    weight: 1.3,
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    url: "https://ai.meta.com/blog/rss/",
    kind: "rss",
    category: "labs",
    weight: 1.25,
  },
  {
    id: "microsoft-ai",
    name: "Microsoft AI",
    url: "https://blogs.microsoft.com/ai/feed/",
    kind: "rss",
    category: "labs",
    weight: 1.1,
  },
  {
    id: "nvidia-ai",
    name: "NVIDIA AI",
    url: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    kind: "rss",
    category: "semiconductors",
    weight: 1.35,
  },
  {
    id: "sia",
    name: "Semiconductor Industry Association",
    url: "https://www.semiconductors.org/feed/",
    kind: "rss",
    category: "semiconductors",
    weight: 1.15,
  },
  {
    id: "nist-ai",
    name: "NIST AI News",
    url: "https://www.nist.gov/news-events/news/rss.xml",
    kind: "rss",
    category: "policy",
    weight: 1.25,
  },
  {
    id: "white-house",
    name: "White House Briefing Room",
    url: "https://www.whitehouse.gov/briefing-room/feed/",
    kind: "rss",
    category: "policy",
    weight: 1,
  },
  {
    id: "arxiv-ai",
    name: "arXiv AI/ML/CL",
    url: "search_query=cat:cs.AI+OR+cat:cs.LG+OR+cat:cs.CL+OR+cat:stat.ML&sortBy=submittedDate&sortOrder=descending&max_results=35",
    kind: "arxiv",
    category: "research",
    weight: 1.2,
  },
  {
    id: "arxiv-bio-ai",
    name: "arXiv Bio + AI",
    url: "search_query=(cat:q-bio.QM+OR+cat:q-bio.BM+OR+cat:cs.LG)+AND+all:%22artificial+intelligence%22&sortBy=submittedDate&sortOrder=descending&max_results=18",
    kind: "arxiv",
    category: "bio",
    weight: 1.1,
  },
  {
    id: "swe-bench",
    name: "SWE-bench Releases",
    url: "https://github.com/swe-bench/SWE-bench/releases.atom",
    kind: "atom",
    category: "benchmarks",
    weight: 1.2,
  },
  {
    id: "livecodebench",
    name: "LiveCodeBench Releases",
    url: "https://github.com/LiveCodeBench/LiveCodeBench/releases.atom",
    kind: "atom",
    category: "benchmarks",
    weight: 1.15,
  },
  {
    id: "helm",
    name: "HELM Releases",
    url: "https://github.com/stanford-crfm/helm/releases.atom",
    kind: "atom",
    category: "benchmarks",
    weight: 1.05,
  },
  {
    id: "hn-frontier",
    name: "Hacker News AI Radar",
    url: "query=(OpenAI%20OR%20Anthropic%20OR%20DeepMind%20OR%20xAI%20OR%20Grok%20OR%20Llama%20OR%20Gemini)%20AI&tags=story",
    kind: "hn",
    category: "frontier_ai",
    weight: 1,
  },
  {
    id: "hn-creators",
    name: "Creator Discourse Radar",
    url: "query=(Karpathy%20OR%20Theo%20OR%20t3.gg%20OR%20Dwarkesh%20OR%20Noam%20Brown%20OR%20swyx)&tags=story",
    kind: "hn",
    category: "creators",
    weight: 0.9,
  },
];
